[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "optimization_solver"
version = "0.0.1"
requires.python = ">=3.10"

authors = [
	{name = "Daniel Kecman"}
]

dependencies = [
	"data_containers"
]